language: node_js
node_js:
- 8.10.0
install: npm install
services:
  - postgresql
env:
- SECRET_KEY=839745FJKSDJKPLDFJFOIWRSFD ADMIN_PASSWORD=andela2018 USER_PASSWORD=sarriball
script: npm test
after_success: npm run coveralls